name: .NET Build for Windows and Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET for Windows
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies for Windows
      run: dotnet restore
    - name: Publish for Windows (win-x64, AOT)
      run: dotnet publish --configuration Release --self-contained --runtime win-x64 -p:PublishAot=true -o ./publish
    - name: Upload build artifacts for Windows
      uses: actions/upload-artifact@v3
      with:
        name: win64-build
        path: ./publish

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET for Linux
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies for Linux
      run: dotnet restore
    - name: Publish for Linux (linux-x64, AOT)
      run: dotnet publish --configuration Release --self-contained --runtime linux-x64 -p:PublishAot=true -o ./publish
    - name: Upload build artifacts for Linux
      uses: actions/upload-artifact@v3
      with:
        name: linux64-build
        path: ./publish
