name: .NET Build for Windows and Linux

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Execute build script on Windows
        if: runner.os == 'Windows'
        run: |
          pwsh -Command "./build.ps1"

      - name: Execute build script on Linux
        if: runner.os == 'Linux'
        run: |
          pwsh -Command "./build.ps1"

      - name: Upload Windows build artifacts
        if: runner.os == 'Windows' && success()
        uses: actions/upload-artifact@v3
        with:
          name: windows-build-artifacts
          path: |
            ./papt/bin/Release/net8.0/win-x64/publish/papt.exe

      - name: Upload Linux build artifacts
        if: runner.os == 'Linux' && success()
        uses: actions/upload-artifact@v3
        with:
          name: linux-build-artifacts
          path: |
            ./papt/bin/Release/net8.0/linux-x64/publish/papt
