name: .NET Build with Flexible Release

on:
  push:
    branches: ["master"]
    tags:
      - "v*"
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest"]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Execute build script
        run: |
          pwsh -Command "./build.ps1"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-artifacts
          path: |
            ./bin/Release/${{ runner.os == 'Windows' && 'win-x64' || 'linux-x64' }}/publish/*

  release:
    needs: build
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Build Type: ${{ github.event_name }}
            Artifacts:
            - Windows: papt.exe
            - Linux: papt
          files: |
            ./artifacts/Windows-latest-artifacts/papt.exe
            ./artifacts/Ubuntu-latest-artifacts/papt
          draft: false
          prerelease: false